FROM node:21-alpine as builder

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install --production

COPY . .

RUN npm run build

FROM nginx:latest

COPY --from=builder /app/build/ /usr/share/nginx/html
